<a href="https://colab.research.google.com/github/Matinnorouzi2023/data-science/blob/main/1D_Numpy_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a = ["0", 1, "two", "3", 4]

In [2]:
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [3]:
import numpy as np

In [4]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [5]:
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


### Checking NumPy Version

The version string is stored under **version** attribute.

In [8]:
print(np.__version__)

1.23.5


<h3 id="type">Type</h3>

In [9]:
type(a)

numpy.ndarray

As numpy arrays contain data of the same type, we can use the attribute "dtype" to obtain the data type of the array’s elements. In this case, it's a 64-bit integer:

In [11]:
a.dtype

dtype('int64')

### Try it yourself

Check the type of the array and Value type for the given array **b**


In [12]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

# Enter your code here

In [15]:
type(b)

b.dtype

dtype('float64')

<details><summary>Click here for the solution</summary>

```python
type(b)
    
b.dtype
    
If we examine the attribute dtype we see float 64, as the elements are not integers:
```

</details>

<h3 id="val">Assign value</h3>

We can change the value of the array. Consider the array <code>c</code>:

In [13]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

We can change the first element of the array to 100 as follows:

In [16]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

We can change the 5th element of the array to 0 as follows:

In [17]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

### Try it yourself

Assign the value 20 for the second element in the given array.

In [18]:
a = np.array([10, 2, 30, 40,50])

# Enter your code here

<details><summary>Click here for the solution</summary>

```python
a[1]=20
a
   
```

</details>


<h3 id="slice">Slicing</h3>

Like lists, we can slice the numpy array. Slicing in python means taking the elements from the given index to another given index.

We pass slice like this: [start:end].

We can select the elements from 1 to 3 and assign it to a new numpy array d as follows:

In [19]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

We can assign the corresponding indexes to new values as follows:

In [20]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

We can also define the steps in slicing, like this: \[start\:end:step].

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


If we don't pass start its considered 0

In [22]:
print(arr[:4])

[1 2 3 4]


If we don't pass end it considers till the length of array

In [23]:
print(arr[4:])

[5 6 7]


If we don't pass step its considered 1

In [24]:
print(arr[1:5:])

[2 3 4 5]


### Try it yourself

Print the even elements in the given array.


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Enter your code here

<details><summary>Click here for the solution</summary>

```python
print(arr[1:8:2])

    
```

</details>


In [28]:
print(arr[1:8:2])


[2 4 6 8]


<h3 id="list">Assign Value with List</h3>

Similarly, we can use a list to select more than one specific index.
The list `select` contains several values:


In [26]:
# Create the index list

select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

We can assign the specified elements to a new value. For example, we can assign the values to 100 000 as follows:

In [29]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

<h3 id="other">Other Attributes</h3>

Let's review some basic array attributes using the array <code>a</code>:

In [30]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

The attribute <code>size</code> is the number of elements in the array:

In [31]:
# Get the size of numpy array

a.size

5

The next two attributes will make more sense when we get to higher dimensions but let's review them. The attribute <code>ndim</code> represents the number of array dimensions, or the rank of the array. In this case, one:


In [32]:
# Get the number of dimensions of numpy array

a.ndim

1

The attribute <code>shape</code> is a tuple of integers indicating the size of the array in each dimension:

In [34]:
# Get the shape/size of numpy array

a.shape

(5,)

### Try it yourself

Find the size ,dimension and shape for the given array **b**

In [35]:
b = np.array([10, 20, 30, 40, 50, 60, 70])

# Enter your code here

<details><summary>Click here for the solution</summary>

```python
b.size

b.ndim

b.shape

    
```

</details>

In [38]:
b.size

b.ndim

b.shape

(7,)

### Numpy Statistical Functions

In [39]:
# Create a numpy array

a = np.array([1, -1, 1, -1])

In [40]:
# Get the mean of numpy array

mean = a.mean()
mean

0.0

In [41]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

1.0

In [42]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [43]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

5

In [44]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

-1